/**
 * The Feed round's icon data (round v4, QĐ-32: Phosphor), taken from the
 * approved mock.
 *
 * WHAT IT WRITES
 *   components/feed/icon/paths.ts   every glyph's name and its one path
 *
 * WHERE FROM
 *   prototype/explore/feed/icons/*.svg — the files the Feed mock draws with,
 *   copied there from Phosphor v2 (`@phosphor-icons/core@2`, regular weight,
 *   plus the `-fill` weight of the few glyphs the mock fills for an on-state;
 *   `prototype/explore/BUILD.md`, "Icons"). Phosphor is MIT: its licence
 *   stands beside the data, `components/feed/icon/LICENSE`.
 *
 * HOW
 *   Nothing is installed and nothing is fetched. Every file is read as text
 *   and must be exactly what Phosphor ships: one <svg> on the 256-unit grid,
 *   filled with currentColor, holding one <path>. Anything else stops the
 *   script rather than being skipped, because a glyph drawn some other way
 *   would not take the text colour the way the mock's does (`feed.js` paints
 *   every icon with currentColor through a mask; the app draws the same path
 *   filled with currentColor).
 *
 * WHEN TO RUN IT
 *   After an icon is added to, changed in or removed from the mock's folder.
 *   `scripts/feed-icons.test.ts` fails until it has run.
 *
 *     npx tsx scripts/feed-icons.ts
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const SOURCE_DIR = join(ROOT, "prototype/explore/feed/icons");
export const OUT = join(ROOT, "components/feed/icon/paths.ts");

export interface FeedIconSource {
  /** The file name without `.svg`: `bag`, `bag-fill`, `magnifying-glass`. */
  name: string;
  /** The glyph's one path, on Phosphor's 256-unit grid. */
  d: string;
}

/** Phosphor's own markup, and nothing else: one path, the 256 grid, currentColor. */
const SHAPE =
  /^<svg xmlns="http:\/\/www\.w3\.org\/2000\/svg" viewBox="0 0 256 256" fill="currentColor"><path d="([^"]+)"\/><\/svg>$/;

/** A path of Phosphor's commands and numbers only. */
const PATH = /^M[\d.,\-MmLlHhVvCcSsQqTtAaZz ]+$/;

/** One glyph from its file, or an error naming the file that is not Phosphor's shape. */
export function parseIcon(name: string, svg: string): FeedIconSource {
  const d = svg.trim().match(SHAPE)?.[1];
  if (!d || !PATH.test(d)) {
    throw new Error(
      `${name}.svg is not one Phosphor path on the 256 grid filled with currentColor — ` +
        "copy the file from @phosphor-icons/core@2 unchanged",
    );
  }
  return { name, d };
}

/**
 * Every glyph in the mock's folder, in code-point order of the name, so the
 * generated file does not depend on the directory listing or the locale.
 */
export function readIcons(dir: string = SOURCE_DIR): FeedIconSource[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith(".svg"))
    .map((f) => f.slice(0, -".svg".length))
    .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
    .map((name) => parseIcon(name, readFileSync(join(dir, `${name}.svg`), "utf8")));
}

/** `components/feed/icon/paths.ts`, byte for byte. */
export function renderIconModule(icons: FeedIconSource[]): string {
  const names = icons.map((i) => `  ${JSON.stringify(i.name)},`).join("\n");
  const paths = icons
    .map((i) => `  ${/^[a-z]+$/.test(i.name) ? i.name : JSON.stringify(i.name)}: ${JSON.stringify(i.d)},`)
    .join("\n");
  return `// Generated by scripts/feed-icons.ts from prototype/explore/feed/icons/ — do not edit by hand.
// Run \`npx tsx scripts/feed-icons.ts\` after the mock's icon folder changes;
// scripts/feed-icons.test.ts fails until it has run.
//
// Phosphor Icons v2 (@phosphor-icons/core), MIT licence: see ./LICENSE.

/**
 * Every glyph the Feed mock draws with (${icons.length}): Phosphor's regular
 * weight, and \`-fill\` for the filled weight of a glyph in its on-state.
 */
export const FEED_ICON_NAMES = [
${names}
] as const;

export type FeedIconName = (typeof FEED_ICON_NAMES)[number];

/** Each glyph's one path on Phosphor's 256-unit grid, filled with the text colour. */
export const FEED_ICON_PATHS: Readonly<Record<FeedIconName, string>> = {
${paths}
};
`;
}

function main(): void {
  const icons = readIcons();
  writeFileSync(OUT, renderIconModule(icons));
  console.log(`feed icons       ${OUT} (${icons.length} glyphs from ${SOURCE_DIR})`);
}

if (process.argv[1] !== undefined && pathToFileURL(process.argv[1]).href === import.meta.url) {
  main();
}
