/**
 * Turns the fixture in `data/` into `supabase/seed.sql`.
 *
 * DESIGN.md §9 rule 1: seed data is never invented and never typed by hand.
 * `data/catalog.ts` and `data/promotions.ts` stay the single source of truth
 * for the sample catalogue, and this script is the only thing allowed to
 * restate them in SQL — which is why `supabase/seed.sql` carries a "generated"
 * banner and why `scripts/gen-seed.test.ts` fails the moment the file on disk
 * and the fixture disagree.
 *
 * The output is deterministic: fixed statement order, fixed row order, fixed
 * column order, no timestamp of its own. Running the script twice on an
 * unchanged fixture produces the same bytes, so a regeneration never shows up
 * as a diff unless the data really moved.
 *
 * Run it with `npm run seed:gen`.
 */

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { FIXTURE_CATALOG } from "@/data/fixture-catalog";
import { SIZES } from "@/data/types";
import type { CatalogInput } from "@/lib/catalog";

// ───────────────────────────────────────────────────────────────── literals
/** A SQL string literal. Single quotes double, the way Postgres wants them. */
const str = (value: string): string => `'${value.replace(/'/g, "''")}'`;

/** A SQL timestamptz literal. The `+07:00` in the text is the whole point. */
const ts = (iso: string): string => `'${iso}'::timestamptz`;

/** A number, or SQL `null` — `undefined` and `null` mean the same here. */
const num = (value: number | null | undefined): string =>
  value === null || value === undefined ? "null" : String(value);

/** A timestamptz that may be absent (`Product.soldOutAt`). */
const tsOrNull = (iso: string | null | undefined): string =>
  iso === null || iso === undefined ? "null" : ts(iso);

/**
 * One `insert` statement, or nothing at all when the list is empty.
 *
 * Empty is not expected for any of the six, but `values ()` with no rows is a
 * syntax error rather than a no-op, so it is worth not emitting.
 */
function insert(table: string, columns: string[], rows: string[][]): string {
  if (rows.length === 0) return "";
  const body = rows.map((cells) => `  (${cells.join(", ")})`).join(",\n");
  return `insert into public.${table} (${columns.join(", ")}) values\n${body};\n`;
}

// ────────────────────────────────────────────────────────────────── the SQL
/**
 * The seed script for one catalogue.
 *
 * Only the `seed_*` mirrors are filled. The live tables are built from them by
 * `reset_demo()`, called on the last line — so the same statement that seeds a
 * fresh database is also what the demo's reset button will run later.
 */
export function renderSeedSql(input: CatalogInput): string {
  const parts: string[] = [];

  parts.push(
    [
      "-- Generated by scripts/gen-seed.ts. Do not edit by hand.",
      "--",
      "-- Source of truth: data/catalog.ts and data/promotions.ts. Regenerate with",
      "-- `npm run seed:gen`; scripts/gen-seed.test.ts fails if the two have drifted.",
      "--",
      "-- Loaded by `supabase db reset` after every migration ([db.seed] in",
      "-- supabase/config.toml). It fills the seed_* mirrors, then reset_demo()",
      "-- rebuilds the live tables from them.",
      "",
      "truncate table",
      "  public.seed_stock_cells,",
      "  public.seed_product_colors,",
      "  public.seed_products,",
      "  public.seed_teasers,",
      "  public.seed_promotions,",
      "  public.seed_drops;",
      "",
    ].join("\n"),
  );

  parts.push(
    insert(
      "seed_drops",
      ["no", "opens_at", "closes_at"],
      input.drops.map((d) => [num(d.no), ts(d.opensAt), ts(d.closesAt)]),
    ),
  );

  parts.push(
    insert(
      "seed_products",
      [
        "id",
        "slug",
        "name",
        "kind",
        "family",
        "material",
        "fit",
        "price_vnd",
        "cut_units",
        "drop_no",
        "sold_out_at",
        "position",
      ],
      input.products.map((p, index) => [
        str(p.id),
        str(p.slug),
        str(p.name),
        str(p.kind),
        str(p.family),
        str(p.material),
        str(p.fit),
        num(p.priceVnd),
        num(p.cutUnits),
        num(p.dropNo),
        tsOrNull(p.soldOutAt),
        num(index),
      ]),
    ),
  );

  // Colour order is band order, so the index inside `Product.colors` is the
  // position, and `photoKeys[i]` is the photo standing in for that colour.
  const colorRows: string[][] = [];
  const stockRows: string[][] = [];
  for (const product of input.products) {
    product.colors.forEach((color, index) => {
      const photoKey = product.photoKeys[index];
      if (photoKey === undefined) {
        throw new Error(`${product.slug}: no photo key for colour ${color}`);
      }
      colorRows.push([str(product.id), str(color), num(index), str(photoKey)]);

      const perSize = product.stock[color];
      if (perSize === undefined) {
        throw new Error(`${product.slug}: no stock for colour ${color}`);
      }
      for (const size of SIZES) {
        stockRows.push([str(product.id), str(color), str(size), num(perSize[size])]);
      }
    });
  }

  parts.push(
    insert("seed_product_colors", ["product_id", "color", "position", "photo_key"], colorRows),
  );
  parts.push(insert("seed_stock_cells", ["product_id", "color", "size", "on_hand"], stockRows));

  parts.push(
    insert(
      "seed_teasers",
      ["slug", "name", "kind", "family", "drop_no", "photo_key", "position"],
      input.teasers.map((t, index) => [
        str(t.slug),
        str(t.name),
        str(t.kind),
        str(t.family),
        num(t.dropNo),
        str(t.photoKey),
        num(index),
      ]),
    ),
  );

  parts.push(
    insert(
      "seed_promotions",
      [
        "code",
        "kind",
        "percent",
        "max_discount_vnd",
        "amount_vnd",
        "starts_at",
        "ends_at",
        "usage_limit",
        "used_count",
        "min_order_vnd",
        "position",
      ],
      // The three shapes are a discriminated union in `data/types.ts` and a
      // check constraint in SQL: a PERCENT row carries no amount, an AMOUNT
      // row carries no cap. Narrowing here keeps both honest.
      input.promotions.map((promo, index) => [
        str(promo.code),
        str(promo.kind),
        num(promo.kind === "PERCENT" ? promo.percent : null),
        num(promo.kind === "PERCENT" ? promo.maxDiscountVnd : null),
        num(promo.kind === "AMOUNT" ? promo.amountVnd : null),
        ts(promo.startsAt),
        ts(promo.endsAt),
        num(promo.usageLimit),
        num(promo.usedCount),
        num(promo.minOrderVnd),
        num(index),
      ]),
    ),
  );

  parts.push("-- Build the live tables from the mirrors just filled.\nselect public.reset_demo();\n");

  return parts.filter((part) => part !== "").join("\n");
}

/**
 * The fixture as a `CatalogInput`.
 *
 * The same four arrays `lib/db/catalog.ts#catalogInput` hands to the browser,
 * rebuilt here rather than imported from it: that module is `server-only` and
 * pulls in the Supabase client, neither of which belongs in a build script or
 * in a Node test runner.
 */
export function fixtureInput(): CatalogInput {
  return {
    products: [...FIXTURE_CATALOG.products],
    drops: [...FIXTURE_CATALOG.drops],
    teasers: [...FIXTURE_CATALOG.teasers],
    promotions: [...FIXTURE_CATALOG.promotions],
  };
}

/** Where the generated file goes, relative to this script. */
export const SEED_PATH = resolve(dirname(fileURLToPath(import.meta.url)), "../supabase/seed.sql");

// Only when run as a command, never when the test imports the renderer.
if (process.argv[1] !== undefined && pathToFileURL(process.argv[1]).href === import.meta.url) {
  writeFileSync(SEED_PATH, renderSeedSql(fixtureInput()), "utf8");
  process.stdout.write(`wrote ${SEED_PATH}\n`);
}
