import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { SEED_PATH, fixtureCustomers, fixtureInput, renderSeedSql } from "./gen-seed";

/** The one call every assertion below compares against. */
const render = () => renderSeedSql(fixtureInput(), fixtureCustomers());

/**
 * The anti-drift catch.
 *
 * `supabase/seed.sql` is generated, and a generated file that nobody checks is
 * a file that silently stops matching its source. Edit a price in
 * `data/catalog.ts`, forget `npm run seed:gen`, and the app would show one
 * number while the database held another — with every unit test still green,
 * because they all read the fixture. This test is what turns that into a red
 * run.
 *
 * It needs no database: it compares text with text.
 */
describe("supabase/seed.sql", () => {
  const onDisk = readFileSync(SEED_PATH, "utf8");

  it("is exactly what the generator produces from data/*.ts", () => {
    expect(onDisk).toBe(render());
  });

  it("says it is generated, so nobody edits it by hand", () => {
    expect(onDisk.startsWith("-- Generated by scripts/gen-seed.ts")).toBe(true);
  });

  it("ends by rebuilding the live tables from the mirrors", () => {
    expect(onDisk.trimEnd().endsWith("select public.reset_demo();")).toBe(true);
  });
});

describe("the generator itself", () => {
  const sql = render();

  it("writes one row per fixture entry — 21 · 38 · 152 · 4 · 2 · 6 · 8 · 9", () => {
    const rowsOf = (table: string) => {
      const start = sql.indexOf(`insert into public.${table} (`);
      expect(start, `no insert for ${table}`).toBeGreaterThan(-1);
      const end = sql.indexOf(";\n", start);
      return sql.slice(start, end).split("\n").length - 1;
    };

    expect(rowsOf("seed_drops")).toBe(4);
    expect(rowsOf("seed_products")).toBe(21);
    expect(rowsOf("seed_product_colors")).toBe(38);
    expect(rowsOf("seed_stock_cells")).toBe(152);
    expect(rowsOf("seed_teasers")).toBe(2);
    expect(rowsOf("seed_promotions")).toBe(6);
    expect(rowsOf("seed_customers")).toBe(8);
    expect(rowsOf("seed_addresses")).toBe(9);
  });

  it("stores every phone as ten digits, however the fixture punctuates it", () => {
    const start = sql.indexOf("insert into public.seed_customers (");
    const block = sql.slice(start, sql.indexOf(";\n", start));
    for (const quoted of block.match(/'0[^']*'/g) ?? []) {
      expect(quoted).toMatch(/^'0\d{9}'$/);
    }
  });

  it("writes every instant as a literal that still carries +07:00", () => {
    const stamps = sql.match(/'[^']*'::timestamptz/g) ?? [];
    expect(stamps.length).toBeGreaterThan(0);
    for (const stamp of stamps) {
      expect(stamp).toMatch(/^'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\+07:00'::timestamptz$/);
    }
  });

  it("is deterministic: the same fixture renders the same bytes", () => {
    expect(render()).toBe(sql);
  });

  it("escapes a quote in a name instead of ending the literal", () => {
    const input = fixtureInput();
    const quoted = renderSeedSql(
      {
        ...input,
        products: [{ ...input.products[0]!, name: "KH'ÓI" }, ...input.products.slice(1)],
      },
      fixtureCustomers(),
    );
    expect(quoted).toContain("'KH''ÓI'");
  });
});
