import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { FIXTURE_CATALOG } from "@/data/fixture-catalog";
import { ORDERS } from "@/data/orders";
import {
  SEED_PATH,
  fixtureCustomers,
  fixtureInput,
  fixtureOrders,
  fixtureStates,
  renderSeedSql,
} from "./gen-seed";

/** The one call every assertion below compares against. */
const render = () =>
  renderSeedSql(fixtureInput(), fixtureCustomers(), fixtureOrders(), fixtureStates());

/** The rows of one `insert`, as the lines of text between the header and `;`. */
function rowsIn(sql: string, table: string): string[] {
  const start = sql.indexOf(`insert into public.${table} (`);
  expect(start, `no insert for ${table}`).toBeGreaterThan(-1);
  const end = sql.indexOf(";\n", start);
  return sql.slice(start, end).split("\n").slice(1);
}

/**
 * The anti-drift catch.
 *
 * `supabase/seed.sql` is generated, and a generated file that nobody checks is
 * a file that silently stops matching its source. Edit a price in
 * `data/catalog.ts`, forget `npm run seed:gen`, and the app would show one
 * number while the database held another — with every unit test still green,
 * because they all read the fixture. This test is what turns that into a red
 * run.
 *
 * It needs no database: it compares text with text.
 */
describe("supabase/seed.sql", () => {
  const onDisk = readFileSync(SEED_PATH, "utf8");

  it("is exactly what the generator produces from data/*.ts", () => {
    expect(onDisk).toBe(render());
  });

  it("says it is generated, so nobody edits it by hand", () => {
    expect(onDisk.startsWith("-- Generated by scripts/gen-seed.ts")).toBe(true);
  });

  it("ends by rebuilding the live tables from the mirrors, on the real clock's anchor", () => {
    expect(onDisk.trimEnd().endsWith("select public.reset_demo(public.demo_anchor());")).toBe(true);
  });
});

describe("the generator itself", () => {
  const sql = render();

  // Slice B5 added the eight fixed styles: 8 styles, 17 colours, 68 cells.
  it("writes one row per fixture entry — 29 · 55 · 220 · 4 · 2 · 6 · 8 · 9 · 24 · 33", () => {
    const rowsOf = (table: string) => rowsIn(sql, table).length;

    expect(rowsOf("seed_drops")).toBe(4);
    expect(rowsOf("seed_products")).toBe(29);
    expect(rowsOf("seed_product_colors")).toBe(55);
    expect(rowsOf("seed_stock_cells")).toBe(220);
    expect(rowsOf("seed_teasers")).toBe(2);
    expect(rowsOf("seed_promotions")).toBe(6);
    expect(rowsOf("seed_customers")).toBe(8);
    expect(rowsOf("seed_addresses")).toBe(9);
    expect(rowsOf("seed_orders")).toBe(24);
    expect(rowsOf("seed_order_lines")).toBe(33);
  });

  it("stores every phone as ten digits, however the fixture punctuates it", () => {
    const start = sql.indexOf("insert into public.seed_customers (");
    const block = sql.slice(start, sql.indexOf(";\n", start));
    for (const quoted of block.match(/'0[^']*'/g) ?? []) {
      expect(quoted).toMatch(/^'0\d{9}'$/);
    }
  });

  it("stores every order's phone as ten digits too", () => {
    // The column checks `phone ~ '^0[0-9]{9}$'`; the fixture copies the
    // customer's number as typed, spaces and all.
    for (const row of rowsIn(sql, "seed_orders")) {
      // code, handle, email, recipient, phone — the fifth quoted literal.
      const phone = row.match(/'[^']*'/g)?.[4];
      expect(phone).toMatch(/^'0\d{9}'$/);
    }
  });

  it("writes every instant as a literal that still carries +07:00", () => {
    const stamps = sql.match(/'[^']*'::timestamptz/g) ?? [];
    expect(stamps.length).toBeGreaterThan(0);
    for (const stamp of stamps) {
      expect(stamp).toMatch(/^'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\+07:00'::timestamptz$/);
    }
  });

  it("is deterministic: the same fixture renders the same bytes", () => {
    expect(render()).toBe(sql);
  });

  it("escapes a quote in a name instead of ending the literal", () => {
    const input = fixtureInput();
    const quoted = renderSeedSql(
      {
        ...input,
        products: [{ ...input.products[0]!, name: "KH'ÓI" }, ...input.products.slice(1)],
      },
      fixtureCustomers(),
      fixtureOrders(),
      fixtureStates(),
    );
    expect(quoted).toContain("'KH''ÓI'");
  });

  // Slice B12: `seed_teasers.announced_at`, when each sample teaser was announced.
  // Its English (slice B15) follows it: name_en, kind_en.
  it("writes each teaser's announcement after its position, as the fixture authors it", () => {
    const start = sql.indexOf("insert into public.seed_teasers (");
    expect(sql.slice(start, sql.indexOf("\n", start))).toBe(
      "insert into public.seed_teasers (slug, name, kind, family, drop_no, photo_key, position, announced_at, name_en, kind_en) values",
    );
    expect(rowsIn(sql, "seed_teasers")).toEqual([
      "  ('s06-soi', 'SỎI', 'Áo khoác dù', 'JACKET', 6, 'suong', 0, '2026-09-18T12:00:00+07:00'::timestamptz, null, 'Nylon jacket'),",
      "  ('s06-ngoi', 'NGÓI', 'Áo hoodie in', 'HOODIE', 6, 'nguoi', 1, '2026-09-18T12:00:00+07:00'::timestamptz, null, 'Printed hoodie')",
    ]);
  });

  it("writes null for a teaser with no announcement, never a guess", () => {
    const input = fixtureInput();
    const unknown = renderSeedSql(
      { ...input, teasers: [{ ...input.teasers[0]!, announcedAt: null }] },
      fixtureCustomers(),
      fixtureOrders(),
      fixtureStates(),
    );
    expect(rowsIn(unknown, "seed_teasers")).toEqual([
      "  ('s06-soi', 'SỎI', 'Áo khoác dù', 'JACKET', 6, 'suong', 0, null, null, 'Nylon jacket')",
    ]);
  });

  // Slice B6: `seed_products.details`, the style's construction lines.
  describe("the construction lines", () => {
    const rows = rowsIn(sql, "seed_products");
    /** A style's row, without the comma that separates it from the next. */
    const rowOf = (id: string) => rows.find((r) => r.startsWith(`  ('${id}'`))!.replace(/,$/, "");

    // The English (slice B15) follows them: name_en, kind_en, material_en, details_en.
    it("come after the position in seed_products, before the English", () => {
      const start = sql.indexOf("insert into public.seed_products (");
      const header = sql.slice(start, sql.indexOf("\n", start));
      expect(header).toBe(
        "insert into public.seed_products (id, slug, name, kind, family, material, fit, " +
          "price_vnd, cut_units, drop_no, sold_out_at, position, details, name_en, kind_en, material_en, details_en) values",
      );
    });

    it("are written as a text[] of the fixture's lines, in their order", () => {
      const lines = FIXTURE_CATALOG.byId.get("p-khoi" as never)!.details;
      expect(lines).toHaveLength(4);
      expect(rowOf("p-khoi")).toContain(`, 0, array[${lines.map((l) => `'${l}'`).join(", ")}]::text[], `);
      // A double quote inside a line is just a character of the literal.
      expect(rowOf("p-bui")).toContain(`'In "Bản đồ mòn" ở ngực trên'`);
    });

    it("are an empty text[] for a style with none", () => {
      // Never an empty English list (`details_en` is null or holds a line), so
      // this is the Vietnamese column wherever it appears.
      expect(rowOf("p-reu")).toContain(", array[]::text[], ");
      expect(rowOf("p-ao-thun-tron")).toContain(", array[]::text[], ");
      const withLines = rows.filter((r) => !r.includes(", array[]::text[], "));
      expect(withLines).toHaveLength(10);
    });

    it("escape a quote in a line instead of ending the literal", () => {
      const input = fixtureInput();
      const quoted = renderSeedSql(
        {
          ...input,
          products: [{ ...input.products[0]!, details: ["Cổ bo gân 2,5 cm", "Túi 'kangaroo'"] }, ...input.products.slice(1)],
        },
        fixtureCustomers(),
        fixtureOrders(),
        fixtureStates(),
      );
      expect(quoted).toContain("array['Cổ bo gân 2,5 cm', 'Túi ''kangaroo''']::text[]");
    });
  });

  // Slice B15: the English of every style and teaser, null where there is none.
  describe("the English", () => {
    const rows = rowsIn(sql, "seed_products");
    const rowOf = (id: string) => rows.find((r) => r.startsWith(`  ('${id}'`))!.replace(/,$/, "");
    const quoted = (lines: readonly string[]) => `array[${lines.map((l) => `'${l}'`).join(", ")}]::text[]`;

    /** The fixture with the first style's (KHÓI's) English replaced by `en`. */
    const withEnglish = (en: object | undefined) => () => {
      const input = fixtureInput();
      const { en: _english, ...khoi } = input.products[0]!;
      const first = en === undefined ? khoi : { ...khoi, en };
      return renderSeedSql(
        { ...input, products: [first, ...input.products.slice(1)] },
        fixtureCustomers(),
        fixtureOrders(),
        fixtureStates(),
      );
    };

    it("writes a style's English name, kind, material and lines last, in that order", () => {
      const khoi = FIXTURE_CATALOG.byId.get("p-khoi" as never)!;
      expect(khoi.en?.details).toHaveLength(4);
      expect(rowOf("p-khoi").endsWith(`, null, 'Oversized tee', 'Cotton 250gsm', ${quoted(khoi.en!.details!)})`)).toBe(true);
    });

    it("writes a fixed style's English name, and null for a style's lines when it has none", () => {
      expect(rowOf("p-ao-thun-tron").endsWith(", 'PLAIN TEE', 'Tee', 'Cotton 220gsm', null)")).toBe(true);
      expect(rowOf("p-reu").endsWith(", null, 'Puffer jacket', 'Quilted down', null)")).toBe(true);
      // Lines in English exactly where there are lines in Vietnamese: Số 05's ten.
      expect(rows.filter((r) => r.replace(/,$/, "").endsWith("]::text[])"))).toHaveLength(10);
    });

    it("writes four nulls for a style with no English at all", () => {
      expect(rowsIn(withEnglish(undefined)(), "seed_products")[0]!.endsWith(", null, null, null, null),")).toBe(true);
    });

    it("escapes a quote in the English instead of ending the literal", () => {
      const sqlOut = withEnglish({ name: "SMOKE'S", details: ["Print 'smoke'"] })();
      expect(rowsIn(sqlOut, "seed_products")[0]).toContain(", 'SMOKE''S', null, null, array['Print ''smoke''']::text[]),");
    });

    it("refuses a blank English field or an empty list of lines, naming the entry", () => {
      expect(withEnglish({ kind: "  " })).toThrow("p-khoi: en.kind is blank");
      expect(withEnglish({ details: [] })).toThrow("p-khoi: en.details is an empty list; leave it out instead");
      expect(withEnglish({ details: ["Kangaroo pocket", " "] })).toThrow("p-khoi: en.details[1] is blank");
      const input = fixtureInput();
      expect(() =>
        renderSeedSql(
          { ...input, teasers: [{ ...input.teasers[0]!, en: { name: "" } }] },
          fixtureCustomers(),
          fixtureOrders(),
          fixtureStates(),
        ),
      ).toThrow("s06-soi: en.name is blank");
    });
  });
});

/**
 * The orders' own anti-drift catch: the seed carries the fixture's orders,
 * all of them, each with its lines — and the numbering the database takes
 * over from them (`order_seq`, `reset_demo()`) starts after the last one.
 */
describe("the sample orders in the seed", () => {
  const sql = render();
  const orderRows = rowsIn(sql, "seed_orders");
  const lineRows = rowsIn(sql, "seed_order_lines");
  const codeOf = (row: string) => /^ {2}\('(DH-\d+)'/.exec(row)?.[1];

  it("holds exactly the fixture's orders, in the fixture's order", () => {
    expect(orderRows.map(codeOf)).toEqual(ORDERS.map((o) => String(o.code)));
  });

  it("keeps every code distinct", () => {
    const codes = orderRows.map(codeOf);
    expect(new Set(codes).size).toBe(codes.length);
  });

  it("gives every order at least one line, and every line an order", () => {
    const withLines = new Set(lineRows.map(codeOf));
    for (const code of orderRows.map(codeOf)) {
      expect(withLines.has(code), `${code} has no line`).toBe(true);
    }
    const known = new Set(orderRows.map(codeOf));
    for (const code of withLines) expect(known.has(code), `${code} is not an order`).toBe(true);
  });

  it("writes as many lines as the fixture's orders carry", () => {
    expect(lineRows).toHaveLength(ORDERS.reduce((n, o) => n + o.lines.length, 0));
  });

  it("ends on DH-2431, the number the database carries on from", () => {
    const numbers = orderRows.map((row) => Number(codeOf(row)!.slice(3)));
    expect(Math.max(...numbers)).toBe(2431);
  });

  // Slice B10: state, due_at, paid_at, shipped_at, tracking_code, delivered_at, cancelled_at, cancel_reason.
  describe("the steps each order passed", () => {
    const row = (code: string) => orderRows.find((r) => codeOf(r) === code)!;
    const at = (iso: string) => `'${iso}'::timestamptz`;

    it("writes a delivered order's payment and hand-over beside its delivery", () => {
      // The mock's DH-1496. No tracking code was ever recorded for a delivered sample order.
      expect(row("DH-2416")).toContain(
        `'DELIVERED', null, ${at("2026-09-11T21:52:00+07:00")}, ${at("2026-09-13T08:20:00+07:00")}, null, ` +
          `${at("2026-09-16T10:02:00+07:00")}, null, null`,
      );
    });

    it("writes no payment for a COD order, which pays at the door", () => {
      expect(row("DH-2415")).toContain(
        `'DELIVERED', null, null, ${at("2026-09-13T08:25:00+07:00")}, null, ${at("2026-09-15T16:45:00+07:00")}, null, null`,
      );
    });

    it("writes an order on its way with its payment and its own hand-over and tracking code", () => {
      expect(row("DH-2422")).toContain(
        `'SHIPPING', null, ${at("2026-09-14T10:33:00+07:00")}, ${at("2026-09-18T07:15:00+07:00")}, 'VD-8842-1907', null, null, null`,
      );
    });

    it("leaves a waiting or cancelled order as it was", () => {
      expect(row("DH-2430")).toContain(`'AWAITING_TRANSFER', ${at("2026-09-21T19:50:00+07:00")}, null, null, null, null, null, null`);
      expect(row("DH-2310")).toContain(
        `'CANCELLED', null, null, null, null, null, ${at("2026-06-07T08:15:00+07:00")}, 'quá hạn chuyển khoản'`,
      );
    });

    it("refuses a moment its own status contradicts", () => {
      const doctored = ORDERS.map((o) =>
        o.code === "DH-2416" ? { ...o, moments: { ...o.moments, deliveredAt: "2026-09-17T10:02:00+07:00" } } : o,
      );
      expect(() => renderSeedSql(fixtureInput(), fixtureCustomers(), doctored, fixtureStates())).toThrow(
        "DH-2416: moments.deliveredAt 2026-09-17T10:02:00+07:00 is not its status's 2026-09-16T10:02:00+07:00",
      );
    });
  });
});

/**
 * Slice B9: what the demo accounts keep — the first one's four saved styles,
 * its reminder and its sizes — written into three mirrors, and nothing written
 * the fixture does not hold.
 */
describe("what the demo accounts keep, in the seed", () => {
  const sql = render();

  it("writes the first account's four saved styles, newest first, each in its colour", () => {
    expect(rowsIn(sql, "seed_favorites")).toEqual([
      "  ('c-minhanh', 0, 'p-bui', 'black'),",
      "  ('c-minhanh', 1, 'p-than', 'navy'),",
      "  ('c-minhanh', 2, 'p-muoi', 'grey'),",
      "  ('c-minhanh', 3, 'p-hoodie-tron', 'grey')",
    ]);
  });

  it("writes its reminder for Số 06 and nobody else's", () => {
    expect(rowsIn(sql, "seed_reminders")).toEqual(["  ('c-minhanh', 6)"]);
  });

  it("writes its sizes and all four switches on — one settings row, for it alone", () => {
    expect(rowsIn(sql, "seed_account_settings")).toEqual([
      "  ('c-minhanh', 'L', 'M', true, true, true, true)",
    ]);
  });

  it("empties the three mirrors with the rest before filling them", () => {
    const head = sql.slice(0, sql.indexOf(";\n") + 1);
    for (const table of ["seed_favorites", "seed_reminders", "seed_account_settings"]) {
      expect(head).toContain(`public.${table},`);
    }
  });

  /** The fixture with the first account's state replaced by `patch`. */
  const withState = (patch: object) => {
    const states = new Map(fixtureStates());
    const first = states.get("c-minhanh" as never)!;
    states.set("c-minhanh" as never, { ...first, ...patch });
    return () => renderSeedSql(fixtureInput(), fixtureCustomers(), fixtureOrders(), states);
  };

  it("refuses a saved style the catalogue does not have", () => {
    const run = withState({ favorites: [{ productId: "p-khong-co", color: "black", savedAt: null }] });
    expect(run).toThrow(/p-khong-co\) is not in the catalogue/);
  });

  it("refuses a colour the style is not made in", () => {
    const run = withState({ favorites: [{ productId: "p-bui", color: "navy", savedAt: null }] });
    expect(run).toThrow(/has no colour navy/);
  });

  it("refuses the same style saved twice", () => {
    const bui = { productId: "p-bui", color: "black", savedAt: null };
    expect(withState({ favorites: [bui, bui] })).toThrow(/is saved twice/);
  });

  it("refuses a moment on a saved style — the mirror has nowhere to put one", () => {
    const run = withState({
      favorites: [{ productId: "p-bui", color: "black", savedAt: "2026-09-18T12:00:00+07:00" }],
    });
    expect(run).toThrow(/carries a moment/);
  });

  it("refuses a reminder for an issue the fixture does not have", () => {
    expect(withState({ reminders: [9] })).toThrow(/issue 9, which the fixture does not have/);
  });

  it("refuses a state kept by somebody who is not a demo account", () => {
    const states = new Map(fixtureStates());
    states.set("c-nobody" as never, states.get("c-minhanh" as never)!);
    expect(() =>
      renderSeedSql(fixtureInput(), fixtureCustomers(), fixtureOrders(), states),
    ).toThrow(/c-nobody: keeps a state but is not a demo account/);
  });
});
