import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { FIXTURE_CATALOG } from "@/data/fixture-catalog";
import { ORDERS } from "@/data/orders";
import {
  SEED_PATH,
  fixtureCustomers,
  fixtureInput,
  fixtureOrders,
  renderSeedSql,
} from "./gen-seed";

/** The one call every assertion below compares against. */
const render = () => renderSeedSql(fixtureInput(), fixtureCustomers(), fixtureOrders());

/** The rows of one `insert`, as the lines of text between the header and `;`. */
function rowsIn(sql: string, table: string): string[] {
  const start = sql.indexOf(`insert into public.${table} (`);
  expect(start, `no insert for ${table}`).toBeGreaterThan(-1);
  const end = sql.indexOf(";\n", start);
  return sql.slice(start, end).split("\n").slice(1);
}

/**
 * The anti-drift catch.
 *
 * `supabase/seed.sql` is generated, and a generated file that nobody checks is
 * a file that silently stops matching its source. Edit a price in
 * `data/catalog.ts`, forget `npm run seed:gen`, and the app would show one
 * number while the database held another — with every unit test still green,
 * because they all read the fixture. This test is what turns that into a red
 * run.
 *
 * It needs no database: it compares text with text.
 */
describe("supabase/seed.sql", () => {
  const onDisk = readFileSync(SEED_PATH, "utf8");

  it("is exactly what the generator produces from data/*.ts", () => {
    expect(onDisk).toBe(render());
  });

  it("says it is generated, so nobody edits it by hand", () => {
    expect(onDisk.startsWith("-- Generated by scripts/gen-seed.ts")).toBe(true);
  });

  it("ends by rebuilding the live tables from the mirrors, on the real clock's anchor", () => {
    expect(onDisk.trimEnd().endsWith("select public.reset_demo(public.demo_anchor());")).toBe(true);
  });
});

describe("the generator itself", () => {
  const sql = render();

  // Slice B5 added the eight fixed styles: 8 styles, 17 colours, 68 cells.
  it("writes one row per fixture entry — 29 · 55 · 220 · 4 · 2 · 6 · 8 · 9 · 24 · 33", () => {
    const rowsOf = (table: string) => rowsIn(sql, table).length;

    expect(rowsOf("seed_drops")).toBe(4);
    expect(rowsOf("seed_products")).toBe(29);
    expect(rowsOf("seed_product_colors")).toBe(55);
    expect(rowsOf("seed_stock_cells")).toBe(220);
    expect(rowsOf("seed_teasers")).toBe(2);
    expect(rowsOf("seed_promotions")).toBe(6);
    expect(rowsOf("seed_customers")).toBe(8);
    expect(rowsOf("seed_addresses")).toBe(9);
    expect(rowsOf("seed_orders")).toBe(24);
    expect(rowsOf("seed_order_lines")).toBe(33);
  });

  it("stores every phone as ten digits, however the fixture punctuates it", () => {
    const start = sql.indexOf("insert into public.seed_customers (");
    const block = sql.slice(start, sql.indexOf(";\n", start));
    for (const quoted of block.match(/'0[^']*'/g) ?? []) {
      expect(quoted).toMatch(/^'0\d{9}'$/);
    }
  });

  it("stores every order's phone as ten digits too", () => {
    // The column checks `phone ~ '^0[0-9]{9}$'`; the fixture copies the
    // customer's number as typed, spaces and all.
    for (const row of rowsIn(sql, "seed_orders")) {
      // code, handle, email, recipient, phone — the fifth quoted literal.
      const phone = row.match(/'[^']*'/g)?.[4];
      expect(phone).toMatch(/^'0\d{9}'$/);
    }
  });

  it("writes every instant as a literal that still carries +07:00", () => {
    const stamps = sql.match(/'[^']*'::timestamptz/g) ?? [];
    expect(stamps.length).toBeGreaterThan(0);
    for (const stamp of stamps) {
      expect(stamp).toMatch(/^'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\+07:00'::timestamptz$/);
    }
  });

  it("is deterministic: the same fixture renders the same bytes", () => {
    expect(render()).toBe(sql);
  });

  it("escapes a quote in a name instead of ending the literal", () => {
    const input = fixtureInput();
    const quoted = renderSeedSql(
      {
        ...input,
        products: [{ ...input.products[0]!, name: "KH'ÓI" }, ...input.products.slice(1)],
      },
      fixtureCustomers(),
      fixtureOrders(),
    );
    expect(quoted).toContain("'KH''ÓI'");
  });

  // Slice B6: `seed_products.details`, the style's construction lines.
  describe("the construction lines", () => {
    const rows = rowsIn(sql, "seed_products");
    /** A style's row, without the comma that separates it from the next. */
    const rowOf = (id: string) => rows.find((r) => r.startsWith(`  ('${id}'`))!.replace(/,$/, "");

    it("are the last column of seed_products", () => {
      const start = sql.indexOf("insert into public.seed_products (");
      const header = sql.slice(start, sql.indexOf("\n", start));
      expect(header).toBe(
        "insert into public.seed_products (id, slug, name, kind, family, material, fit, " +
          "price_vnd, cut_units, drop_no, sold_out_at, position, details) values",
      );
    });

    it("are written as a text[] of the fixture's lines, in their order", () => {
      const lines = FIXTURE_CATALOG.byId.get("p-khoi" as never)!.details;
      expect(lines).toHaveLength(4);
      expect(rowOf("p-khoi").endsWith(`, array[${lines.map((l) => `'${l}'`).join(", ")}]::text[])`)).toBe(true);
      // A double quote inside a line is just a character of the literal.
      expect(rowOf("p-bui")).toContain(`'In "Bản đồ mòn" ở ngực trên'`);
    });

    it("are an empty text[] for a style with none", () => {
      expect(rowOf("p-reu").endsWith(", array[]::text[])")).toBe(true);
      expect(rowOf("p-ao-thun-tron").endsWith(", array[]::text[])")).toBe(true);
      const withLines = rows.filter((r) => !r.replace(/,$/, "").endsWith(", array[]::text[])"));
      expect(withLines).toHaveLength(10);
    });

    it("escape a quote in a line instead of ending the literal", () => {
      const input = fixtureInput();
      const quoted = renderSeedSql(
        {
          ...input,
          products: [{ ...input.products[0]!, details: ["Cổ bo gân 2,5 cm", "Túi 'kangaroo'"] }, ...input.products.slice(1)],
        },
        fixtureCustomers(),
        fixtureOrders(),
      );
      expect(quoted).toContain("array['Cổ bo gân 2,5 cm', 'Túi ''kangaroo''']::text[]");
    });
  });
});

/**
 * The orders' own anti-drift catch: the seed carries the fixture's orders,
 * all of them, each with its lines — and the numbering the database takes
 * over from them (`order_seq`, `reset_demo()`) starts after the last one.
 */
describe("the sample orders in the seed", () => {
  const sql = render();
  const orderRows = rowsIn(sql, "seed_orders");
  const lineRows = rowsIn(sql, "seed_order_lines");
  const codeOf = (row: string) => /^ {2}\('(DH-\d+)'/.exec(row)?.[1];

  it("holds exactly the fixture's orders, in the fixture's order", () => {
    expect(orderRows.map(codeOf)).toEqual(ORDERS.map((o) => String(o.code)));
  });

  it("keeps every code distinct", () => {
    const codes = orderRows.map(codeOf);
    expect(new Set(codes).size).toBe(codes.length);
  });

  it("gives every order at least one line, and every line an order", () => {
    const withLines = new Set(lineRows.map(codeOf));
    for (const code of orderRows.map(codeOf)) {
      expect(withLines.has(code), `${code} has no line`).toBe(true);
    }
    const known = new Set(orderRows.map(codeOf));
    for (const code of withLines) expect(known.has(code), `${code} is not an order`).toBe(true);
  });

  it("writes as many lines as the fixture's orders carry", () => {
    expect(lineRows).toHaveLength(ORDERS.reduce((n, o) => n + o.lines.length, 0));
  });

  it("ends on DH-2431, the number the database carries on from", () => {
    const numbers = orderRows.map((row) => Number(codeOf(row)!.slice(3)));
    expect(Math.max(...numbers)).toBe(2431);
  });
});
