// GENERATED by tools/sweep/gen.mjs from tools/sweep/template.js and tools/sweep/manifest.mjs. Do not edit:
// change the manifest or the template, then generate again.
// Selection "all", vi: 153 entries. Rewrite with `npm run sweep:gen -- --legacy`.
/**
 * Layout sweep — the separate visual pass QĐ-14 requires.
 *
 * Behavioural tests and "zero horizontal overflow" do not imply "the grid
 * looks like a grid". This walks the routes of `tools/sweep/manifest.mjs`,
 * screenshots each one, opens each layer, and runs seven detectors that only
 * a real viewport can answer.
 *
 * THIS FILE IS THE TEMPLATE. `tools/sweep/gen.mjs` writes the selection into
 * the slot below and saves a runnable copy (`.playwright-cli/sweep-<label>-<lang>.js`,
 * and `tools/layout-sweep.js` for the full Vietnamese pass). Edit the routes in
 * the manifest and the detectors here, never in a generated copy.
 *
 * Run a copy through the CLI session so the browser stays visible:
 *
 *   npx playwright cli --raw run-code --filename=.playwright-cli/sweep-all-vi.js \
 *     > .playwright-cli/sweep-all-vi.json
 *
 * The file must hold exactly one function expression — `run-code` wraps it in
 * parentheses and evaluates it, so no import/require here, and no URL class.
 */
async (page) => {
  const ORIGIN = "http://127.0.0.1:3200";
  const PLAN = {
    "lang": "vi",
    "shots": ".playwright-cli/shots",
    "heights": { "390": 844, "1280": 800 },
    "volatile": ["[role=\"timer\"]"],
    "scope": {
      "label": "all",
      "lang": "vi",
      "full": true,
      "zone": "all",
      "routes": [],
      "tags": [],
      "overlays": [],
      "widths": null,
      "impact": null,
      "entries": 153,
    },
    "shopPages": [
      { "route": "/", "width": 390, "name": "home-390" },
      { "route": "/products", "width": 390, "name": "products-390" },
      { "route": "/products/s05-khoi", "width": 390, "name": "products-s05-khoi-390" },
      { "route": "/products/ao-thun-tron", "width": 390, "name": "products-ao-thun-tron-390" },
      { "route": "/search?q=khoi", "width": 390, "name": "search-q-khoi-390" },
      { "route": "/cart", "width": 390, "name": "cart-390" },
      { "route": "/checkout", "width": 390, "name": "checkout-390" },
      { "route": "/order-confirmed", "width": 390, "name": "order-confirmed-390" },
      { "route": "/order-confirmed/DH-2430", "width": 390, "name": "order-confirmed-DH-2430-390" },
      { "route": "/track?code=DH-2425&phone=0908221447", "width": 390, "name": "track-code-DH-2425&phone-0908221447-390" },
      { "route": "/track", "width": 390, "name": "track-390" },
      { "route": "/khong-co-trang-nay", "width": 390, "name": "khong-co-trang-nay-390" },
      { "route": "/so/999", "width": 390, "name": "so-999-390" },
      { "route": "/faq", "width": 390, "name": "faq-390" },
      { "route": "/faq?q=cod", "width": 390, "name": "faq-q-cod-390" },
      { "route": "/size-guide", "width": 390, "name": "size-guide-390" },
      { "route": "/about", "width": 390, "name": "about-390" },
      { "route": "/contact", "width": 390, "name": "contact-390" },
      { "route": "/privacy", "width": 390, "name": "privacy-390" },
      { "route": "/returns", "width": 390, "name": "returns-390" },
      { "route": "/so/4", "width": 390, "name": "so-4-390" },
      { "route": "/so/5", "width": 390, "name": "so-5-390" },
      { "route": "/sign-in", "width": 390, "name": "sign-in-390" },
      { "route": "/sign-up", "width": 390, "name": "sign-up-390" },
      { "route": "/forgot-password", "width": 390, "name": "forgot-password-390" },
      { "route": "/account", "width": 390, "name": "account-390" },
      { "route": "/account/profile", "width": 390, "name": "account-profile-390" },
      { "route": "/account/password", "width": 390, "name": "account-password-390" },
      { "route": "/account/orders", "width": 390, "name": "account-orders-390" },
      { "route": "/account/notifications", "width": 390, "name": "account-notifications-390" },
      { "route": "/account/orders/DH-2430", "width": 390, "name": "account-orders-DH-2430-390" },
      { "route": "/account/orders/DH-2310", "width": 390, "name": "account-orders-DH-2310-390" },
      { "route": "/account/orders/DH-2310/tracking", "width": 390, "name": "account-orders-DH-2310-tracking-390" },
      { "route": "/account/addresses", "width": 390, "name": "account-addresses-390" },
      { "route": "/account/addresses/new", "width": 390, "name": "account-addresses-new-390" },
      { "route": "/account/wishlist", "width": 390, "name": "account-wishlist-390" },
      { "route": "/", "width": 1280, "name": "home-1280" },
      { "route": "/products", "width": 1280, "name": "products-1280" },
      { "route": "/products/s05-khoi", "width": 1280, "name": "products-s05-khoi-1280" },
      { "route": "/products/ao-thun-tron", "width": 1280, "name": "products-ao-thun-tron-1280" },
      { "route": "/search?q=khoi", "width": 1280, "name": "search-q-khoi-1280" },
      { "route": "/cart", "width": 1280, "name": "cart-1280" },
      { "route": "/checkout", "width": 1280, "name": "checkout-1280" },
      { "route": "/order-confirmed", "width": 1280, "name": "order-confirmed-1280" },
      { "route": "/order-confirmed/DH-2430", "width": 1280, "name": "order-confirmed-DH-2430-1280" },
      { "route": "/track?code=DH-2425&phone=0908221447", "width": 1280, "name": "track-code-DH-2425&phone-0908221447-1280" },
      { "route": "/track", "width": 1280, "name": "track-1280" },
      { "route": "/khong-co-trang-nay", "width": 1280, "name": "khong-co-trang-nay-1280" },
      { "route": "/so/999", "width": 1280, "name": "so-999-1280" },
      { "route": "/faq", "width": 1280, "name": "faq-1280" },
      { "route": "/faq?q=cod", "width": 1280, "name": "faq-q-cod-1280" },
      { "route": "/size-guide", "width": 1280, "name": "size-guide-1280" },
      { "route": "/about", "width": 1280, "name": "about-1280" },
      { "route": "/contact", "width": 1280, "name": "contact-1280" },
      { "route": "/privacy", "width": 1280, "name": "privacy-1280" },
      { "route": "/returns", "width": 1280, "name": "returns-1280" },
      { "route": "/so/4", "width": 1280, "name": "so-4-1280" },
      { "route": "/so/5", "width": 1280, "name": "so-5-1280" },
      { "route": "/sign-in", "width": 1280, "name": "sign-in-1280" },
      { "route": "/sign-up", "width": 1280, "name": "sign-up-1280" },
      { "route": "/forgot-password", "width": 1280, "name": "forgot-password-1280" },
      { "route": "/account", "width": 1280, "name": "account-1280" },
      { "route": "/account/profile", "width": 1280, "name": "account-profile-1280" },
      { "route": "/account/password", "width": 1280, "name": "account-password-1280" },
      { "route": "/account/orders", "width": 1280, "name": "account-orders-1280" },
      { "route": "/account/notifications", "width": 1280, "name": "account-notifications-1280" },
      { "route": "/account/orders/DH-2430", "width": 1280, "name": "account-orders-DH-2430-1280" },
      { "route": "/account/orders/DH-2310", "width": 1280, "name": "account-orders-DH-2310-1280" },
      { "route": "/account/orders/DH-2310/tracking", "width": 1280, "name": "account-orders-DH-2310-tracking-1280" },
      { "route": "/account/addresses", "width": 1280, "name": "account-addresses-1280" },
      { "route": "/account/addresses/new", "width": 1280, "name": "account-addresses-new-1280" },
      { "route": "/account/wishlist", "width": 1280, "name": "account-wishlist-1280" },
    ],
    "shopOverlays": [
      {
        "route": "/account/addresses?add=1#province",
        "width": 390,
        "name": "account-addresses-add-province-390",
        "open": async ({ page }) => {
          await page.locator("#f-province").click();
        },
      },
      {
        "route": "/account/addresses?add=1#province",
        "width": 1280,
        "name": "account-addresses-add-province-1280",
        "open": async ({ page }) => {
          await page.locator("#f-province").click();
        },
      },
    ],
    "adminPages": [
      { "route": "/admin", "width": 1280, "name": "admin-1280" },
      { "route": "/admin/orders", "width": 1280, "name": "admin-orders-1280" },
      { "route": "/admin/orders/DH-2429", "width": 1280, "name": "admin-orders-DH-2429-1280" },
      { "route": "/admin/orders/DH-2430", "width": 1280, "name": "admin-orders-DH-2430-1280" },
      { "route": "/admin/orders/DH-2418", "width": 1280, "name": "admin-orders-DH-2418-1280" },
      { "route": "/admin/drops", "width": 1280, "name": "admin-drops-1280" },
      { "route": "/admin/drops/05", "width": 1280, "name": "admin-drops-05-1280" },
      { "route": "/admin/promotions", "width": 1280, "name": "admin-promotions-1280" },
      { "route": "/admin/products", "width": 1280, "name": "admin-products-1280" },
      { "route": "/admin/products?drop=5", "width": 1280, "name": "admin-products-drop-5-1280" },
      { "route": "/admin/products/new", "width": 1280, "name": "admin-products-new-1280" },
      { "route": "/admin/products/p-khoi", "width": 1280, "name": "admin-products-p-khoi-1280" },
      { "route": "/admin/products/p-ao-thun-tron", "width": 1280, "name": "admin-products-p-ao-thun-tron-1280" },
      { "route": "/admin/customers", "width": 1280, "name": "admin-customers-1280" },
      { "route": "/admin/customers/c-minhanh", "width": 1280, "name": "admin-customers-c-minhanh-1280" },
      { "route": "/admin/slips?codes=DH-2429", "width": 1280, "name": "admin-slips-codes-DH-2429-1280" },
      { "route": "/admin/slips?codes=DH-2429,DH-2428,DH-2423,DH-2426", "width": 1280, "name": "admin-slips-codes-DH-2429,DH-2428,DH-2423,DH-2426-1280" },
      { "route": "/admin/slips?codes=DH-9999", "width": 1280, "name": "admin-slips-codes-DH-9999-1280" },
      { "route": "/admin/log", "width": 1280, "name": "admin-log-1280" },
      { "route": "/admin?days=7", "width": 1280, "name": "admin-days-7-1280" },
      { "route": "/admin?days=30", "width": 1280, "name": "admin-days-30-1280" },
      { "route": "/admin/log?kind=order", "width": 1280, "name": "admin-log-kind-order-1280" },
      { "route": "/admin/log?today=1", "width": 1280, "name": "admin-log-today-1-1280" },
      { "route": "/admin/log?q=zzz", "width": 1280, "name": "admin-log-q-zzz-1280" },
      { "route": "/admin/customers?group=loyal", "width": 1280, "name": "admin-customers-group-loyal-1280" },
      { "route": "/admin/customers?q=zzz", "width": 1280, "name": "admin-customers-q-zzz-1280" },
      { "route": "/admin/customers/c-namle", "width": 1280, "name": "admin-customers-c-namle-1280" },
      { "route": "/admin/promotions?state=ENDED", "width": 1280, "name": "admin-promotions-state-ENDED-1280" },
      { "route": "/admin/promotions?state=PAUSED", "width": 1280, "name": "admin-promotions-state-PAUSED-1280" },
      { "route": "/admin/drops/04", "width": 1280, "name": "admin-drops-04-1280" },
      { "route": "/admin/drops/06", "width": 1280, "name": "admin-drops-06-1280" },
      { "route": "/admin/drops/99", "width": 1280, "name": "admin-drops-99-1280" },
      { "route": "/admin/products?drop=6", "width": 1280, "name": "admin-products-drop-6-1280" },
      { "route": "/admin/products?drop=4", "width": 1280, "name": "admin-products-drop-4-1280" },
      { "route": "/admin/products?fixed=1&gone=1", "width": 1280, "name": "admin-products-fixed-1&gone-1-1280" },
      { "route": "/admin/products?drop=5&q=zzz", "width": 1280, "name": "admin-products-drop-5&q-zzz-1280" },
      { "route": "/admin/products?drop=99", "width": 1280, "name": "admin-products-drop-99-1280" },
    ],
    "adminOverlays": [
      {
        "route": "/admin/orders/DH-2429#more",
        "width": 1280,
        "name": "admin-order-more-menu-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thao tác khác", "More actions") }).click();
        },
      },
      {
        "route": "/admin/orders/DH-2429#cancel",
        "width": 1280,
        "name": "admin-order-cancel-sheet-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thao tác khác", "More actions") }).click();
          await page.waitForTimeout(250);
          await page.getByRole("menuitem", { name: T("Huỷ đơn", "Cancel order") }).click();
          await page.waitForTimeout(350);
          await page.getByRole("dialog").getByRole("combobox", { name: T("Lý do", "Reason") }).click();
        },
      },
      {
        "route": "/admin/orders/DH-2429#handover",
        "width": 1280,
        "name": "admin-order-handover-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Bàn giao", "Hand over") }).click();
        },
      },
      {
        "route": "/admin/orders/DH-2429#carrier",
        "width": 1280,
        "name": "admin-order-carrier-select-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Bàn giao", "Hand over") }).click();
          await page.waitForTimeout(300);
          await page.getByRole("combobox", { name: T("Hình thức giao", "Delivery service") }).click();
        },
      },
      {
        "route": "/admin/orders/DH-2431#address",
        "width": 1280,
        "name": "admin-order-address-form-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Sửa", "Edit") }).click();
        },
      },
      {
        "route": "/admin/orders/DH-2431#province",
        "width": 1280,
        "name": "admin-order-address-province-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Sửa", "Edit") }).click();
          await page.waitForTimeout(300);
          await page.getByRole("combobox", { name: T("Tỉnh / thành", "Province / city") }).click();
        },
      },
      {
        "route": "/admin/orders/DH-2431#ward",
        "width": 1280,
        "name": "admin-order-address-ward-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Sửa", "Edit") }).click();
          await page.waitForTimeout(300);
          await page.getByRole("combobox", { name: T("Phường / xã", "Ward / commune") }).click();
        },
      },
      {
        "route": "/admin/orders#rowmenu",
        "width": 1280,
        "name": "admin-orders-row-menu-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thao tác DH-2431", "Actions for DH-2431") }).click();
        },
      },
      {
        "route": "/admin#reset",
        "width": 1280,
        "name": "admin-reset-sheet-1280",
        "open": async ({ page, T }) => {
          // Opens the confirmation only; the sweep never presses its button.
          await page.locator("aside").getByRole("button", { name: T("Đặt lại dữ liệu mẫu", "Reset demo data") }).click();
        },
      },
      {
        "route": "/admin#days",
        "width": 1280,
        "name": "admin-overview-day-table-1280",
        "open": async ({ page, T }) => {
          await page.getByText(T("Xem dạng bảng", "View as table")).click();
        },
      },
      {
        "route": "/admin/log#filter",
        "width": 1280,
        "name": "admin-log-filter-fields-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thêm bộ lọc", "Add filter") }).click();
        },
      },
      {
        "route": "/admin/log#filter-values",
        "width": 1280,
        "name": "admin-log-filter-values-1280",
        "open": async ({ page, T, LANG }) => {
          await page.getByRole("button", { name: T("Thêm bộ lọc", "Add filter") }).click();
          await page.waitForTimeout(400);
          await page.getByRole("menuitem", { name: LANG === "en" ? /Action type/ : /Loại thao tác/ }).click();
        },
      },
      {
        "route": "/admin/products#rowmenu",
        "width": 1280,
        "name": "admin-products-row-menu-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thao tác HOODIE TRƠN", "Actions for PLAIN HOODIE"), exact: true }).click();
        },
      },
      {
        "route": "/admin/products#restock",
        "width": 1280,
        "name": "admin-products-restock-sheet-1280",
        "open": async ({ page, T, LANG }) => {
          await page.getByRole("button", { name: T("Thao tác HOODIE TRƠN", "Actions for PLAIN HOODIE"), exact: true }).click();
          await page.getByRole("menuitem").first().waitFor({ state: "visible" });
          await page.waitForTimeout(400); // the menu animates in: a click before it settles can miss (07/10/2026)
          await page.getByRole("menuitem", { name: T("Nhập thêm", "Restock") }).click();
          await page.waitForTimeout(350);
          await page.getByRole("dialog").getByLabel(LANG === "en" ? /^Restock Grey M,/ : /^Nhập thêm Xám M,/).fill("4");
        },
      },
      {
        "route": "/admin/products?drop=5#rowmenu",
        "width": 1280,
        "name": "admin-products-so05-row-menu-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thao tác S05\u00a0\u2013 KHÓI", "Actions for D05\u00a0\u2013 KHÓI"), exact: true }).click();
        },
      },
      {
        "route": "/admin/products?drop=5#adjust",
        "width": 1280,
        "name": "admin-products-adjust-sheet-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thao tác S05\u00a0\u2013 KHÓI", "Actions for D05\u00a0\u2013 KHÓI"), exact: true }).click();
          await page.getByRole("menuitem").first().waitFor({ state: "visible" });
          await page.waitForTimeout(400);
          await page.getByRole("menuitem", { name: T("Điều chỉnh tồn kho", "Adjust stock") }).click();
          await page.waitForTimeout(350);
          // round v5 slice 5a: Arc Select, by role and label.
          await page.getByRole("dialog").getByRole("combobox", { name: T("Lý do", "Reason") }).click();
        },
      },
      {
        "route": "/admin/products?drop=5#filter",
        "width": 1280,
        "name": "admin-products-filter-fields-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thêm bộ lọc", "Add filter") }).click();
        },
      },
      {
        "route": "/admin/products?drop=5#filter-values",
        "width": 1280,
        "name": "admin-products-filter-values-1280",
        "open": async ({ page, T, LANG }) => {
          await page.getByRole("button", { name: T("Thêm bộ lọc", "Add filter") }).click();
          await page.waitForTimeout(400);
          await page.getByRole("menuitem", { name: LANG === "en" ? /Type/ : /Loại/ }).click();
        },
      },
      {
        "route": "/admin/products?drop=5#adjust-ready",
        "width": 1280,
        "name": "admin-products-adjust-ready-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thao tác S05 – KHÓI", "Actions for D05 – KHÓI"), exact: true }).click();
          await page.getByRole("menuitem").first().waitFor({ state: "visible" });
          await page.waitForTimeout(400);
          await page.getByRole("menuitem", { name: T("Điều chỉnh tồn kho", "Adjust stock") }).click();
          await page.waitForTimeout(500);
          await page.getByRole("dialog").getByRole("button", { name: T("Bớt Đen M", "Decrease Black M") }).click();
          await page.getByRole("dialog").getByRole("combobox", { name: T("Lý do", "Reason") }).click();
          await page.waitForTimeout(300);
          await page.getByRole("option", { name: T("Hư hỏng", "Damaged") }).click();
        },
      },
      {
        "route": "/admin/products#adjust-fixed",
        "width": 1280,
        "name": "admin-products-adjust-fixed-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thao tác HOODIE TRƠN", "Actions for PLAIN HOODIE"), exact: true }).click();
          await page.getByRole("menuitem").first().waitFor({ state: "visible" });
          await page.waitForTimeout(400);
          await page.getByRole("menuitem", { name: T("Điều chỉnh tồn kho", "Adjust stock") }).click();
        },
      },
      {
        "route": "/admin/drops#rowmenu",
        "width": 1280,
        "name": "admin-drops-row-menu-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thao tác Số 05", "Actions for Drop 05"), exact: true }).click();
        },
      },
      {
        "route": "/admin/drops#create",
        "width": 1280,
        "name": "admin-drops-create-sheet-1280",
        "open": async ({ page, T }) => {
          // round v5 slice 4: the Arc heading has no v3 `.top`; the page's own "Tạo số".
          await page.getByRole("button", { name: T("Tạo số", "Create drop") }).first().click();
        },
      },
      {
        "route": "/admin/drops#edit",
        "width": 1280,
        "name": "admin-drops-edit-sheet-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thao tác Số 06", "Actions for Drop 06"), exact: true }).click();
          await page.getByRole("menuitem").first().waitFor({ state: "visible" });
          await page.waitForTimeout(400);
          await page.getByRole("menuitem", { name: T("Sửa giờ", "Reschedule") }).click();
        },
      },
      {
        "route": "/admin/drops#close",
        "width": 1280,
        "name": "admin-drops-close-sheet-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thao tác Số 05", "Actions for Drop 05"), exact: true }).click();
          await page.getByRole("menuitem").first().waitFor({ state: "visible" });
          await page.waitForTimeout(400);
          await page.getByRole("menuitem", { name: T("Đóng sớm", "Close early") }).click();
        },
      },
      {
        "route": "/admin/drops/05#teaser",
        "width": 1280,
        "name": "admin-drops-teaser-sheet-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thêm mẫu hé lộ", "Add teaser") }).click();
          await page.waitForTimeout(700);
          // round v5 slice 4: Arc's Select, found by its role and label, not v3's `.field3 button.selbtn`.
          await page.getByRole("dialog").getByRole("combobox", { name: T("Loại", "Type") }).click();
        },
      },
      {
        "route": "/admin/drops#create-backwards",
        "width": 1280,
        "name": "admin-drops-create-backwards-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Tạo số", "Create drop") }).first().click();
          await page.waitForTimeout(700);
          await page.getByRole("dialog").getByLabel(T("Đóng lúc 20:00 ngày", "Closes at 20:00 on")).fill("01/10/2026");
        },
      },
      {
        "route": "/admin/drops/05#close-detail",
        "width": 1280,
        "name": "admin-drops-close-detail-1280",
        "open": async ({ page, T }) => {
          await page.locator("#detail").getByRole("button", { name: T("Đóng sớm", "Close early") }).click();
        },
      },
      {
        "route": "/admin/drops/05#teaser-ready",
        "width": 1280,
        "name": "admin-drops-teaser-ready-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thêm mẫu hé lộ", "Add teaser") }).click();
          await page.waitForTimeout(700);
          await page.getByRole("dialog").getByLabel(T("Tên mẫu", "Style name")).fill("SỎI");
          await page.getByRole("dialog").getByRole("combobox", { name: T("Loại", "Type") }).click();
          await page.waitForTimeout(400);
          await page.getByRole("option", { name: "Áo khoác dù", exact: true }).click();
          await page.waitForTimeout(300);
          await page.getByRole("dialog").getByRole("radio", { name: T("Ảnh tro", "Photo tro") }).click();
        },
      },
      {
        "route": "/admin/drops/04#rowmenu",
        "width": 1280,
        "name": "admin-drops-04-row-menu-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thao tác Số 04", "Actions for Drop 04"), exact: true }).click();
        },
      },
      {
        "route": "/admin/promotions#rowmenu",
        "width": 1280,
        "name": "admin-promotions-row-menu-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thao tác DOT05", "Actions for DOT05"), exact: true }).click();
        },
      },
      {
        "route": "/admin/promotions#create-arc",
        "width": 1280,
        "name": "admin-promotions-create-drawer-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Tạo mã", "Create code") }).click();
          await page.waitForTimeout(700);
          await page.getByRole("dialog").getByRole("combobox", { name: T("Loại", "Type") }).click();
        },
      },
      {
        "route": "/admin/promotions#edit-arc",
        "width": 1280,
        "name": "admin-promotions-edit-drawer-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thao tác DOT05", "Actions for DOT05"), exact: true }).click();
          await page.getByRole("menuitem").first().waitFor({ state: "visible" });
          await page.waitForTimeout(400);
          await page.getByRole("menuitem", { name: T("Sửa", "Edit"), exact: true }).click();
        },
      },
      {
        "route": "/admin/promotions#error-arc",
        "width": 1280,
        "name": "admin-promotions-create-error-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Tạo mã", "Create code") }).click();
          await page.waitForTimeout(700);
          await page.getByRole("dialog").getByRole("button", { name: T("Lưu", "Save") }).click();
        },
      },
      {
        "route": "/admin/customers#rowmenu",
        "width": 1280,
        "name": "admin-customers-row-menu-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Thao tác Trần Minh Anh", "Actions for Trần Minh Anh"), exact: true }).click();
        },
      },
      {
        "route": "/admin/products/new#issue-menu",
        "width": 1280,
        "name": "admin-product-new-issue-menu-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("combobox", { name: T("Số", "Drop"), exact: true }).click();
        },
      },
      {
        "route": "/admin/products/new#fixed",
        "width": 1280,
        "name": "admin-product-new-fixed-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("combobox", { name: T("Số", "Drop"), exact: true }).click();
          await page.waitForTimeout(250);
          await page.getByRole("option", { name: T("Cố định", "Basics") }).click();
        },
      },
      {
        "route": "/admin/products/p-khoi#kind",
        "width": 1280,
        "name": "admin-product-form-kind-menu-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("combobox", { name: T("Loại", "Type") }).click();
        },
      },
      {
        "route": "/admin/products/new#crop",
        "width": 1280,
        "name": "admin-product-new-crop-sheet-1280",
        "open": async ({ page, T, LANG }) => {
          await page.getByRole("group", { name: T("Màu sẽ cắt", "Colours to cut") }).getByRole("button", { name: T("Đen", "Black"), exact: true }).click();
          await page.getByLabel(T("Chọn tệp cho Đen", "Choose file for Black")).setInputFiles("tools/fixtures/soi-den.png");
          await page.getByRole("dialog").getByRole("group", { name: LANG === "en" ? /^4:5 crop frame/ : /^Khung cắt/ }).waitFor({ state: "visible", timeout: 8000 });
        },
      },
      {
        "route": "/admin/products/new#photopick",
        "width": 1280,
        "name": "admin-product-new-photopick-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("group", { name: T("Màu sẽ cắt", "Colours to cut") }).getByRole("button", { name: T("Đen", "Black"), exact: true }).click();
          await page.getByRole("button", { name: T("Mượn tạm", "Borrow") }).first().click();
        },
      },
      {
        "route": "/admin/products/p-khoi#photopick",
        "width": 1280,
        "name": "admin-product-edit-photopick-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Mượn tạm", "Borrow") }).first().click();
        },
      },
      {
        "route": "/admin/products/new#colours",
        "width": 1280,
        "name": "admin-product-new-colours-1280",
        "open": async ({ page, T, LANG }) => {
          for (const c of LANG === "en" ? ["Black", "White", "Grey"] : ["Đen", "Trắng", "Xám"]) {
            await page.getByRole("group", { name: T("Màu sẽ cắt", "Colours to cut") }).getByRole("button", { name: c, exact: true }).click();
          }
        },
      },
      {
        "route": "/admin/products/p-ao-thun-tron#photopick",
        "width": 1280,
        "name": "admin-product-fixed-photopick-1280",
        "open": async ({ page, T }) => {
          await page.getByRole("button", { name: T("Đổi ảnh mượn", "Change borrowed photo") }).first().click();
        },
      },
    ],
  };
  // The language of this run (round v6, QD-40). The cookie is set after the
  // sign-in reset below, and the words the sweep clicks by follow it through `T`.
  const LANG = PLAN.lang;
  const T = (vi, en) => (LANG === "en" ? en : vi);
  const SHOTS = PLAN.shots;

  // Account routes redirect when nobody is signed in, and checkout needs a
  // cart. Slice B1 made the session a real auth cookie, so it is opened by
  // pressing the sign-in screen's own "Đăng nhập thử" rather than by writing
  // a `brand.session` key that no longer exists.
  const SEED = {
    "brand.cart": JSON.stringify({
      v: 1,
      lines: [{ productId: "p-khoi", size: "M", color: "black", qty: 1 }],
    }),
  };

  // `run-code` evaluates this in a sandbox without the global URL class, so
  // the path comes out of the string rather than out of a parser.
  const pathOf = (href) => href.replace(ORIGIN, "").split("?")[0].split("#")[0] || "/";

  // Every console error, with the entry that was on screen when it came.
  let current = "sign-in";
  const consoleErrors = [];
  const onConsole = (m) => {
    if (m.type() === "error") consoleErrors.push({ at: current, url: page.url(), text: m.text() });
  };
  page.on("console", onConsole);
  const foreign = [];
  const onRequest = (r) => {
    if (!r.url().startsWith(ORIGIN)) foreign.push(r.url());
  };
  page.context().on("request", onRequest);

  await page.goto(ORIGIN + "/");
  await page.evaluate((seed) => {
    for (const [k, v] of Object.entries(seed)) localStorage.setItem(k, v);
  }, SEED);
  await page.context().clearCookies();
  await page.context().addCookies([{ name: "hive-lang", value: LANG, url: ORIGIN }]);
  await page.goto(ORIGIN + "/sign-in");
  await page.getByRole("button", { name: T("Đăng nhập thử", "Try a demo account") }).click();
  await page.waitForURL("**/account", { timeout: 20000 });

  // Everything below runs inside the page: only a real viewport knows which
  // media query won, what the computed cursor is, and what is actually
  // reachable at a given point.
  const probe = (width) =>
    page.evaluate((viewportWidth) => {
      const out = {
        inlineBox: [],
        ratioSpread: [],
        loneButton: [],
        arrowCursor: [],
        clipped: [],
        smallTarget: [],
        tinyText: [],
        horizontalOverflow: null,
      };
      const MAX = 6; // per detector, per route — enough to act on, not a dump
      const label = (el) => {
        const id = el.id ? `#${el.id}` : "";
        const cls = typeof el.className === "string" && el.className
          ? `.${el.className.trim().split(/\s+/).join(".")}`
          : "";
        const text = (el.textContent || "").trim().slice(0, 24);
        return `${el.tagName.toLowerCase()}${id}${cls}${text ? ` "${text}"` : ""}`;
      };
      const push = (bucket, entry) => {
        if (bucket.length < MAX) bucket.push(entry);
      };

      // 1. A CSS rule asks for a box only a block can keep, but the element it
      //    lands on is inline. `aspect-ratio` and percentage `width` are then
      //    dropped in silence — this is the bug that shipped mismatched cards.
      const blockOnly = [];
      for (const sheet of document.styleSheets) {
        let rules;
        try {
          rules = sheet.cssRules;
        } catch {
          continue; // cross-origin sheet, nothing to read
        }
        // Every CSSStyleRule carries a `cssRules` list since CSS nesting shipped (empty
        // when the rule nests nothing), so "has cssRules" no longer means "is a group".
        // Read the rule's own declarations first, then descend into whatever it nests.
        // The old order skipped every style rule and reported inlineBox:0 for months.
        const walk = (list) => {
          for (const rule of list) {
            if (rule.selectorText && rule.style) {
              const wants =
                (rule.style.aspectRatio && rule.style.aspectRatio !== "auto" && "aspect-ratio") ||
                (rule.style.width && rule.style.width.endsWith("%") && "width:%") ||
                (rule.style.height && rule.style.height !== "auto" && "height");
              if (wants) blockOnly.push({ selector: rule.selectorText, wants });
            }
            if (rule.cssRules && rule.cssRules.length) walk(rule.cssRules);
          }
        };
        walk(rules);
      }
      // An element under a `display: none` ancestor draws nothing, whatever its
      // own display says: getComputedStyle still answers "inline" for an `<a>`
      // there. Round v6 tooling slice: all 72 findings of the B18 baseline were
      // `.acc-item` links in `.acc-nav`, which is `display: none` below 900px.
      const hiddenAbove = (el) => {
        for (let p = el.parentElement; p; p = p.parentElement) {
          if (getComputedStyle(p).display === "none") return true;
        }
        return false;
      };
      for (const { selector, wants } of blockOnly) {
        let nodes;
        try {
          nodes = document.querySelectorAll(selector);
        } catch {
          continue; // selector the CSSOM accepts but querySelectorAll will not
        }
        for (const el of nodes) {
          const display = getComputedStyle(el).display;
          if ((display === "inline" || display === "inline flow") && !hiddenAbove(el)) {
            push(out.inlineBox, { el: label(el), selector, wants, display });
          }
        }
      }

      // 2. Images sitting in the same grid or flex row must share one ratio,
      //    or the row reads as ragged even though nothing overflows.
      //    Only grids and flex ROWS count as a row: the page frame `.s.v2` is
      //    a flex column, and grouping by it once compared the hero photo
      //    with every card on the page (three false positives, slice 0).
      //    Each image belongs to its nearest row only, so an inner grid's
      //    images never leak into the outer container's set.
      const groups = new Map();
      for (const img of document.images) {
        let p = img.parentElement;
        while (p && p !== document.body) {
          const cs = getComputedStyle(p);
          const isRow =
            (cs.display === "grid" || (cs.display === "flex" && cs.flexDirection.startsWith("row"))) &&
            p.children.length > 1;
          if (isRow) {
            if (!groups.has(p)) groups.set(p, []);
            groups.get(p).push(img);
            break;
          }
          p = p.parentElement;
        }
      }
      for (const [box, imgs] of groups) {
        const ratios = imgs
          .map((i) => i.getBoundingClientRect())
          .filter((r) => r.width > 8 && r.height > 8)
          .map((r) => r.width / r.height);
        if (ratios.length < 2) continue;
        const lo = Math.min(...ratios);
        const hi = Math.max(...ratios);
        if (hi / lo > 1.02) {
          push(out.ratioSpread, {
            container: label(box),
            count: ratios.length,
            spread: +(hi / lo).toFixed(3),
            ratios: ratios.map((r) => +r.toFixed(3)),
          });
        }
      }

      // 3. A button alone in its wrapper is meant to fill it. When it does not,
      //    an `<a class="btn">` beside a `<button class="btn">` go out of line.
      //    `div > .btn:only-child{ width:100% }` is a phone rule — on desktop a
      //    1200px-wide call to action would be the bug, so only check phones.
      if (viewportWidth <= 460) {
        for (const btn of document.querySelectorAll(".btn")) {
          const parent = btn.parentElement;
          if (!parent || parent.children.length !== 1) continue;
          const pw = parent.getBoundingClientRect().width;
          const bw = btn.getBoundingClientRect().width;
          const style = getComputedStyle(parent);
          const inner = pw - parseFloat(style.paddingLeft) - parseFloat(style.paddingRight);
          if (inner - bw > 1) {
            push(out.loneButton, { el: label(btn), buttonWidth: +bw.toFixed(1), wrapperWidth: +inner.toFixed(1) });
          }
        }
      }

      // 4. A control that keeps the arrow cursor does not read as pressable.
      //    Disabled controls are exempt — there the arrow is the honest answer.
      const CONTROLS = 'button, [role="button"], a[href], summary, .chip, .btn, .sz';
      for (const el of document.querySelectorAll(CONTROLS)) {
        if (el.disabled || el.getAttribute("aria-disabled") === "true") continue;
        const r = el.getBoundingClientRect();
        if (r.width < 2 || r.height < 2) continue;
        const cursor = getComputedStyle(el).cursor;
        if (cursor !== "pointer") push(out.arrowCursor, { el: label(el), cursor });
      }

      // 5. Clipped inside an `overflow:hidden` frame. getBoundingClientRect
      //    alone cannot see this — it returns the layout box and says nothing
      //    about an ancestor cutting it — so the rect check is confirmed by
      //    asking what is actually painted at the element's centre.
      for (const el of document.querySelectorAll(CONTROLS)) {
        const r = el.getBoundingClientRect();
        if (r.width < 2 || r.height < 2) continue;
        let p = el.parentElement;
        while (p && p !== document.documentElement) {
          const o = getComputedStyle(p);
          // Inside a scroll container (a long menu in an open sheet, a scrolling
          // panel) everything is reachable by scrolling; the locked body above
          // it must not be read as the frame that cuts it. Slice B3b found six
          // such false alarms in the teaser sheet's kind menu.
          if (
            (/auto|scroll/.test(o.overflowY) && p.scrollHeight > p.clientHeight + 1) ||
            (/auto|scroll/.test(o.overflowX) && p.scrollWidth > p.clientWidth + 1)
          ) break;
          // A swipe strip also overflows its box, but you can reach the rest
          // by scrolling — that is the pattern, not the bug. Only an axis that
          // is cut AND cannot be scrolled hides content for good.
          const cutX = /hidden|clip/.test(o.overflowX) && p.scrollWidth <= p.clientWidth + 1;
          const cutY = /hidden|clip/.test(o.overflowY) && p.scrollHeight <= p.clientHeight + 1;
          if (cutX || cutY) {
            const pr = p.getBoundingClientRect();
            const outside =
              (cutX && (r.left < pr.left - 1 || r.right > pr.right + 1)) ||
              (cutY && (r.top < pr.top - 1 || r.bottom > pr.bottom + 1));
            if (outside) {
              const cx = Math.min(Math.max(r.left + r.width / 2, 0), innerWidth - 1);
              const cy = Math.min(Math.max(r.top + r.height / 2, 0), innerHeight - 1);
              const hit = document.elementFromPoint(cx, cy);
              const reachable = !!(hit && (hit === el || el.contains(hit) || hit.contains(el)));
              // Reachable means the centre is still painted and hittable; only
              // the edge is trimmed, which is usually intended. Unreachable is
              // the real fault: a control nobody can touch.
              if (!reachable) push(out.clipped, { el: label(el), frame: label(p), axis: cutX ? "x" : "y" });
            }
            break;
          }
          p = p.parentElement;
        }
      }

      // 6. PRODUCT.md sets a 44px floor on phones. QĐ-18: measure what is
      //    actually reachable, including whatever is layered on top — a rect
      //    that is big enough means nothing if something else catches the tap.
      //    The size choice is `label.size` (56px, 48 on Hồ sơ), the control a
      //    thumb presses; `.sz` is only the letter inside it, and measuring the
      //    letter reported twelve 10–22px "targets" per run (tooling slice T1).
      const TARGETS = 'button, [role="button"], a[href], summary, .chip, .btn, .size';
      if (viewportWidth <= 460) {
        // Probing the four corners of a 44x44 square demands a square target,
        // which neighbouring items in a row can never give each other. Measure
        // instead how far the element still answers along each axis — that is
        // the hit area a thumb actually gets, `::after` padding included.
        const hits = (el, x, y) => {
          const h = document.elementFromPoint(
            Math.min(Math.max(x, 0), innerWidth - 1),
            Math.min(Math.max(y, 0), innerHeight - 1),
          );
          return !!(h && (h === el || el.contains(h) || h.contains(el)));
        };
        const extent = (el, cx, cy, axis) => {
          let lo = 0;
          let hi = 0;
          for (let d = 1; d <= 30; d++) {
            if (hits(el, axis === "x" ? cx - d : cx, axis === "y" ? cy - d : cy)) lo = d;
            else break;
          }
          for (let d = 1; d <= 30; d++) {
            if (hits(el, axis === "x" ? cx + d : cx, axis === "y" ? cy + d : cy)) hi = d;
            else break;
          }
          return lo + hi;
        };
        for (const el of document.querySelectorAll(TARGETS)) {
          if (el.disabled) continue;
          const r = el.getBoundingClientRect();
          if (r.width < 2 || r.height < 2) continue;
          if (r.width >= 44 && r.height >= 44) continue;
          const cx = r.left + r.width / 2;
          const cy = r.top + r.height / 2;
          if (!hits(el, cx, cy)) continue; // covered by something else entirely
          // elementFromPoint stops answering one pixel inside the far edge, so
          // the stepped extent lands 1px short of the real box: an `::after`
          // measured at exactly 44px probes as 43. Add that pixel back before
          // judging, or every control that just meets the floor reads as a miss.
          const hw = extent(el, cx, cy, "x") + 1;
          const hh = extent(el, cx, cy, "y") + 1;
          if (hw < 44 || hh < 44) {
            push(out.smallTarget, {
              el: label(el),
              layoutBox: `${r.width.toFixed(1)}x${r.height.toFixed(1)}`,
              hitArea: `${hw}x${hh}`,
              short: [hw < 44 ? `w:${44 - hw}px` : null, hh < 44 ? `h:${44 - hh}px` : null].filter(Boolean).join(" "),
            });
          }
        }
      }

      // 7. Type floor (QĐ-22): no visible text under 11px anywhere. Walks text
      //    nodes so a size set on an ancestor is caught where it lands.
      {
        const seen = new Set();
        const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
        let node;
        while ((node = walker.nextNode())) {
          if (!node.nodeValue.trim()) continue;
          const el = node.parentElement;
          if (!el || seen.has(el)) continue;
          seen.add(el);
          if (el.closest(".sr-only, script, style, sup, sub")) continue;
          const cs = getComputedStyle(el);
          if (cs.display === "none" || cs.visibility === "hidden") continue;
          const size = parseFloat(cs.fontSize);
          if (size < 11) push(out.tinyText, { el: label(el), size });
        }
      }

      if (document.documentElement.scrollWidth > innerWidth + 1) {
        out.horizontalOverflow = {
          scrollWidth: document.documentElement.scrollWidth,
          viewport: innerWidth,
        };
      }
      return out;
    }, width);

  // The boxes, in the shot's own pixels, of what changes with the clock alone
  // (`manifest.mjs`, VOLATILE): `pixdiff.mjs --regions` leaves them out.
  const volatile = {};
  const boxes = (name, fullPage) =>
    page
      .evaluate(
        ({ selectors, fullPage }) => {
          const out = [];
          for (const el of document.querySelectorAll(selectors.join(","))) {
            const r = el.getBoundingClientRect();
            if (r.width < 1 || r.height < 1) continue;
            const x = r.left + (fullPage ? scrollX : 0);
            const y = r.top + (fullPage ? scrollY : 0);
            out.push([Math.floor(x), Math.floor(y), Math.ceil(r.width + (x % 1)), Math.ceil(r.height + (y % 1))]);
          }
          return out;
        },
        { selectors: PLAN.volatile, fullPage },
      )
      .then((list) => {
        if (list.length) volatile[name] = list;
      })
      .catch(() => {});

  const results = [];
  const visited = [];
  const record = (entry) => {
    results.push(entry);
    visited.push({
      name: entry.name,
      route: entry.route,
      width: entry.width,
      status: entry.status ?? null,
      landedOn: entry.landedOn ?? null,
      ...(entry.error ? { error: entry.error } : {}),
    });
  };
  let viewportWidth = 0;
  const size = async (width) => {
    if (width === viewportWidth) return;
    await page.setViewportSize({ width, height: PLAN.heights[width] });
    viewportWidth = width;
  };

  // The shop's pages, one width after the other.
  for (const { route, width, name } of PLAN.shopPages) {
    current = name;
    await size(width);
    const entry = { route, width, name };
    try {
      const response = await page.goto(ORIGIN + route, { waitUntil: "load" });
      entry.status = response ? response.status() : null;
      entry.landedOn = pathOf(page.url());
      await page.waitForTimeout(250); // let layout and any client render settle
      await page.screenshot({ path: `${SHOTS}/${name}.png`, fullPage: true });
      await boxes(name, true);
      entry.findings = await probe(width);
    } catch (e) {
      entry.error = String(e).slice(0, 200);
    }
    record(entry);
  }

  // The shop's layers: a menu that is shut measures like a page that has none.
  // Since v4 slice 3a the address form is a sheet on /account/addresses
  // (`?add=1` opens it), and the province picker opens over the sheet.
  for (const { route, width, name, open } of PLAN.shopOverlays) {
    current = name;
    await size(width);
    const entry = { route, width, name };
    try {
      const response = await page.goto(ORIGIN + route.split("#")[0], { waitUntil: "load" });
      entry.status = response ? response.status() : null;
      entry.landedOn = route.split("#")[0];
      await open({ page, T, LANG });
      await page.waitForTimeout(450);
      await page.screenshot({ path: `${SHOTS}/${name}.png`, fullPage: false });
      await boxes(name, false);
      entry.findings = await probe(width);
    } catch (e) {
      entry.error = String(e).slice(0, 200);
    }
    record(entry);
  }

  const visit = async (route, width, name, open) => {
    current = name;
    await size(width);
    const entry = { route, width, name };
    try {
      const response = await page.goto(ORIGIN + route.split("#")[0], { waitUntil: "load" });
      entry.status = response ? response.status() : null;
      entry.landedOn = pathOf(page.url());
      await page.waitForTimeout(250);
      if (open) {
        await open({ page, T, LANG });
        await page.waitForTimeout(450);
      }
      await page.screenshot({ path: `${SHOTS}/${name}.png`, fullPage: !open });
      await boxes(name, !open);
      entry.findings = await probe(width);
    } catch (e) {
      entry.error = String(e).slice(0, 200);
    }
    record(entry);
  };

  // The back office, as the demo manager ("Vào quản trị thử"), desktop only.
  if (PLAN.adminPages.length || PLAN.adminOverlays.length) {
    current = "admin-sign-in";
    await page.setViewportSize({ width: 1280, height: 800 });
    viewportWidth = 1280;
    await page.goto(ORIGIN + "/sign-in");
    await page.getByRole("button", { name: T("Vào quản trị thử", "Try the admin") }).click();
    await page.waitForURL(ORIGIN + "/admin", { timeout: 20000 });
    for (const { route, width, name } of PLAN.adminPages) await visit(route, width, name);
    for (const { route, width, name, open } of PLAN.adminOverlays) await visit(route, width, name, open);
  }

  page.off("console", onConsole);
  page.context().off("request", onRequest);

  const counts = {};
  let total = 0;
  for (const r of results) {
    if (!r.findings) continue;
    for (const [k, v] of Object.entries(r.findings)) {
      const n = Array.isArray(v) ? v.length : v ? 1 : 0;
      counts[k] = (counts[k] || 0) + n;
      total += n;
    }
  }

  return {
    routes: results.length,
    totalFindings: total,
    byDetector: counts,
    consoleErrors,
    foreign,
    redirected: results.filter((r) => r.landedOn && r.landedOn !== r.route.split("?")[0].split("#")[0]).map((r) => `${r.route} -> ${r.landedOn}`),
    results: results.filter((r) => r.error || (r.findings && Object.values(r.findings).some((v) => (Array.isArray(v) ? v.length : v)))),
    shots: SHOTS,
    // Since tooling slice T1: what this run covered, in visit order, so `tools/sweep/diff.mjs` can tell a route
    // that lost its findings from a route this run never opened; the clock's boxes per shot; the selection.
    visited,
    volatile,
    scope: PLAN.scope,
  };
}
